default:
  image: golang:1.27.1-trixie

  cache:
    key:
      files:
        - go.mod
    paths:
      - .go/pkg/mod/

variables:
  GOPATH: $CI_PROJECT_DIR/.go

stages:
  - test
  - build

format:
  stage: test
  script:
    - test -z "$(gofmt -l -- *.go)"

test:
  stage: test
  script:
    - go test ./...

race:
  stage: test
  script:
    - go test -race ./...

vet:
  stage: test
  script:
    - go vet ./...

go-mod-tidy:
  stage: test
  script:
    - go mod tidy -diff

build:
  stage: build
  script:
    - go build ./...
